### ISSUE TITLE
Sensor range setting config

### ISSUE THREAD

**Issue by MAWoodMain** [kriswiner/VL53L0X#1]
hi, I have been adapting your code for my application and I would like to know how to change between operating modes. The data sheet describes:

- Default mode 30ms budget  1.2m, accuracy as per Table 12
- High accuracy 200ms budget 1.2m, accuracy < +/- 3% precise measurement
- Long range 33ms budget  2m, long ranging, only for dark conditions (no IR) 
- High speed 20ms budget  1.2m, accuracy +/- 5% high speed where accuracy is not priority

From my testing your configs seem to put it into long range, how can I get it into default?

**Comment by kriswiner** [comment]
Are you using the Pololu library? I would recommned you do, then these can
easily be selected.

**Comment by MAWoodMain** [comment]
I have ported your library into java, I have seen theirs and it was large so the port time would be huge. Your library had the level of usability I needed, do you know how do change the mode?

**Comment by kriswiner** [comment]
I recomnmend you use the Pololu Arduino library, or just use ST's API. yes
it's large, but then you have access to all of their functions. Without the
register map, it is not possible to create your own librayr per se. The
sketch I wrote was based on guesses and from cribbing from the ST API. I
don't use it myself.

**Comment by MAWoodMain** [comment]
Ah, ok cheers for the advice.

**Comment by sarangpraj** [comment]
Hey kriswiner ,
I am using ST s API(VL53L0X) and i have a doubt regarding changing modes at run time,For my application i want the sensor to work in High accuracy mode first and after  a time it has to work on Fast mode and again back to High accuracy mode.Is it possible ?? if yes how can i implement it on the application
Thank you

**Comment by kriswiner** [comment]
Don't know, just reset and reconfigure to the mode you want?

**Comment by sarangpraj** [comment]
After reset is it necessary to do the initialization(Data Init,Static init.....) again
